### ISSUE TITLE
Stuck when opening chests in path mode in Catalan and Latin

### ISSUE THREAD

**Issue by mrkcxd** [anonymoushackerIV/Duolingo-Pro-2-BETA#7]
The web page will continuously reload when you move to a chest in path mode. DuoPro will automatically open chests in some languages ​​but won't do the same when you learn Catalan and Latin

**Comment by anonymoushackerIV** [comment]
Does the it not open chests in the English to Latin course or Latin learned from another language? Additionally, I can't find Catalan in the Duolingo language options. Which base language are you using to learn Catalan?

Thanks

**Comment by mrkcxd** [comment]
> Does the it not open chests in the English to Latin course or Latin learned from another language? Additionally, I can't find Catalan in the Duolingo language options. Which base language are you using to learn Catalan?

It does not open chests in the Latin from English course and Catalan from Spanish course.

**Comment by anonymoushackerIV** [comment]
Should be fixed now

Thanks for reporting the problem
