### ISSUE TITLE
Duolingo Pro doesnt press the start lesson button, had to press it manually.

### ISSUE THREAD

**Issue by qing762** [anonymoushackerIV/Duolingo-Pro-2-BETA#9]
https://media.discordapp.net/attachments/995904492988006531/1214123557328519209/v64AM6e.png?ex=65f7f7ad&is=65e582ad&hm=5d2c2c5d28abc74edc5a0aa55a8261c68e5dd6d9b496dc273fe7ad2d29b02a49&=&width=490&height=350

No idea why I cant submit images, but its the button beside the `Solve` button

**Comment by anonymoushackerIV** [comment]
try updating to 9.6.1, should have a fix for the issue

btw thanks for reporting it
